CPU_CREDIT_BALANCE:
  Namespace: AWS/EC2
  Instanceid: i-003fa1ea6cf8a6b70
  AlarmDescription: CPU Credit Balance is low
  MetricName: CPUCreditBalance
  Threshold: 10
  Statistic: Average
  ComparisonOperator: LessThanOrEqualToThreshold
  Dimensions:
    - Name: InstanceId
      Value:  i-003fa1ea6cf8a6b70
